# Generated by Django 4.2.7 on 2023-12-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_marketplacemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
